# Generated by Django 5.2.15 on 2026-09-24 15:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edit_window_minutes', models.PositiveIntegerField(default=60, help_text='How long after posting the author may still edit their own post, in minutes. Counted from when the post was created. Set to 0 to stop edits entirely — posts can always still be deleted, by the author or from this admin.')),
            ],
            options={
                'verbose_name': 'Feed settings',
                'verbose_name_plural': 'Feed settings',
                'db_table': 'feed_settings',
            },
        ),
    ]
