# Generated by Django 5.2.15 on 2026-09-24 15:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_feedsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feedsettings',
            name='auto_hide_after_reports',
            field=models.PositiveIntegerField(default=0, help_text='Hide a post automatically once this many different members have reported it, so a problem post stops being visible before a moderator gets to it. Hiding is reversible and the post is still listed here. Set to 0 to never hide automatically — sensible while the member base is small, since a handful of coordinated reports would otherwise be enough to silence anyone.'),
        ),
        migrations.CreateModel(
            name='PostReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(choices=[('SPAM', 'Spam or advertising'), ('MISLEADING', 'Misleading financial claim'), ('ABUSE', 'Abusive or offensive'), ('PRIVACY', "Shares someone's private information"), ('OTHER', 'Something else')], max_length=20)),
                ('detail', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('PENDING', 'Awaiting review'), ('ACTIONED', 'Actioned'), ('DISMISSED', 'Dismissed')], db_index=True, default='PENDING', max_length=20)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='feed.feedpost')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feed_post_report',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('post', 'reporter'), name='unique_post_reporter_report')],
            },
        ),
    ]
