# Generated by Django 5.2.13 on 2026-04-25 14:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('action', models.CharField(choices=[('USER_REGISTERED', 'User Registered'), ('PIN_SET', 'PIN Set'), ('PIN_CHANGED', 'PIN Changed'), ('OTP_SENT', 'OTP Sent'), ('OTP_VERIFIED', 'OTP Verified'), ('KYC_SUBMITTED', 'KYC Submitted'), ('KYC_APPROVED', 'KYC Approved'), ('INVESTMENT_CREATED', 'Investment Created'), ('WITHDRAWAL_REQUESTED', 'Withdrawal Requested'), ('PAYMENT_RECEIVED', 'Payment Received'), ('PROFILE_UPDATED', 'Profile Updated'), ('TERMS_ACCEPTED', 'Terms Accepted')], db_index=True, max_length=50)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('old_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
