# Generated by Django 5.2.13 on 2026-04-26 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('USER_REGISTERED', 'User Registered'), ('PIN_SET', 'PIN Set'), ('PIN_CHANGED', 'PIN Changed'), ('OTP_SENT', 'OTP Sent'), ('OTP_VERIFIED', 'OTP Verified'), ('KYC_SUBMITTED', 'KYC Submitted'), ('KYC_APPROVED', 'KYC Approved'), ('INVESTMENT_CREATED', 'Investment Created'), ('INVESTMENT_CONFIRMED', 'Investment Confirmed'), ('INVESTMENT_CANCELLED', 'Investment Cancelled'), ('WITHDRAWAL_REQUESTED', 'Withdrawal Requested'), ('PAYMENT_RECEIVED', 'Payment Received'), ('PROFILE_UPDATED', 'Profile Updated'), ('TERMS_ACCEPTED', 'Terms Accepted')], db_index=True, max_length=50),
        ),
    ]
