# Generated by Django 5.2.14 on 2026-06-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('USER_REGISTERED', 'User Registered'), ('PIN_SET', 'PIN Set'), ('PIN_CHANGED', 'PIN Changed'), ('OTP_SENT', 'OTP Sent'), ('OTP_VERIFIED', 'OTP Verified'), ('KYC_SUBMITTED', 'KYC Submitted'), ('KYC_APPROVED', 'KYC Approved'), ('KYC_REJECTED', 'KYC Rejected'), ('INVESTMENT_CREATED', 'Investment Created'), ('INVESTMENT_CONFIRMED', 'Investment Confirmed'), ('INVESTMENT_CANCELLED', 'Investment Cancelled'), ('WITHDRAWAL_REQUESTED', 'Withdrawal Requested'), ('PAYMENT_INITIATED', 'Payment Initiated'), ('PAYMENT_RECEIVED', 'Payment Received'), ('PAYMENT_FAILED', 'Payment Failed'), ('PROFILE_UPDATED', 'Profile Updated'), ('TERMS_ACCEPTED', 'Terms Accepted'), ('RECURRING_PLAN_CREATED', 'Recurring Plan Created'), ('RECURRING_PLAN_PAUSED', 'Recurring Plan Paused'), ('GOAL_CREATED', 'Goal Created'), ('WALLET_CREDITED', 'Wallet Credited'), ('WALLET_DEBITED', 'Wallet Debited'), ('NAV_UPDATED', 'NAV Updated'), ('PROFILER_COMPLETED', 'Profiler Completed'), ('REFERRAL_CREATED', 'Referral Created'), ('REFERRAL_CONVERTED', 'Referral Converted'), ('CONSENT_RECORDED', 'Consent Recorded')], db_index=True, max_length=50),
        ),
    ]
