# Generated by Django 5.2.15 on 2026-09-17 07:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0004_alter_recurringplan_frequency'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StandingOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_reference', models.CharField(db_index=True, max_length=12, unique=True)),
                ('standing_order_name', models.CharField(max_length=64)),
                ('custom_sto_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('response_ref_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('reminder_schedule_id', models.CharField(blank=True, default='', max_length=64)),
                ('first_execution_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('frequency', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('phone_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Authorisation'), ('ACTIVE', 'Active'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], db_index=True, default='PENDING', max_length=20)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('recurring_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='standing_orders', to='investments.recurringplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standing_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments_standing_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StandingOrderCharge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('ACTIVATION', 'Activation'), ('DEDUCTION', 'Deduction')], db_index=True, max_length=12)),
                ('transaction_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(choices=[('OKAY', 'Okay'), ('ERROR', 'Error')], db_index=True, max_length=10)),
                ('response_code', models.CharField(blank=True, default='', max_length=10)),
                ('masked_msisdn', models.CharField(blank=True, default='', max_length=32)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('standing_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='payments.standingorder')),
            ],
            options={
                'db_table': 'payments_standing_order_charge',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='standingorder',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'ACTIVE'])), fields=('recurring_plan',), name='unique_live_standing_order_per_plan'),
        ),
    ]
