# Generated by Django 5.2.14 on 2026-06-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('INVESTMENT_CONFIRMED', 'Investment Confirmed'), ('PAYMENT_RECEIVED', 'Payment Received'), ('PAYMENT_FAILED', 'Payment Failed'), ('KYC_APPROVED', 'KYC Approved'), ('KYC_REJECTED', 'KYC Rejected'), ('WITHDRAWAL_PROCESSED', 'Withdrawal Processed'), ('RECURRING_PLAN_EXECUTED', 'Recurring Plan Executed'), ('YIELD_ALERT', 'Yield Alert'), ('REFERRAL_CONVERTED', 'Referral Converted'), ('STATEMENT_READY', 'Statement Ready'), ('PROFILER_COMPLETED', 'Profiler Completed'), ('GENERAL', 'General')], db_index=True, max_length=40),
        ),
    ]
