# Generated by Django 5.2.15 on 2026-09-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('INVESTMENT_CONFIRMED', 'Investment Confirmed'), ('PAYMENT_RECEIVED', 'Payment Received'), ('PAYMENT_FAILED', 'Payment Failed'), ('KYC_APPROVED', 'KYC Approved'), ('KYC_REJECTED', 'KYC Rejected'), ('WITHDRAWAL_PROCESSED', 'Withdrawal Processed'), ('RECURRING_PLAN_EXECUTED', 'Recurring Plan Executed'), ('YIELD_ALERT', 'Yield Alert'), ('REFERRAL_CONVERTED', 'Referral Converted'), ('STATEMENT_READY', 'Statement Ready'), ('PROFILER_COMPLETED', 'Profiler Completed'), ('CONTRIBUTION_DUE', 'Contribution Due'), ('STANDING_ORDER_ACTIVE', 'Standing Order Active'), ('STANDING_ORDER_CHARGED', 'Standing Order Charged'), ('STANDING_ORDER_FAILED', 'Standing Order Failed'), ('GENERAL', 'General')], db_index=True, max_length=40),
        ),
    ]
