from __future__ import annotations

import re

from apps.common.exceptions import ValidationError
from apps.common.validation.text import sanitise_identifier

# Length is bounded before anything else touches these. An unbounded PIN field
# reaches bcrypt, which hashes the whole input — a multi-megabyte "PIN" is a
# free CPU-burn on an unauthenticated endpoint.
PIN_MIN_LENGTH = 4
PIN_MAX_LENGTH = 6
OTP_LENGTH = 6

_DIGITS = re.compile(r"^\d+$")

# Referral codes are generated by us; this only has to reject what we would
# never have issued.
_REFERRAL = re.compile(r"^[A-Z0-9]{4,12}$")


def validate_pin(*, value: str, field: str = "pin") -> str:
    """A numeric PIN of the length we issue. Never logged, never echoed."""
    cleaned = sanitise_identifier(value=value, field=field, max_length=PIN_MAX_LENGTH)
    if not _DIGITS.match(cleaned) or not (
        PIN_MIN_LENGTH <= len(cleaned) <= PIN_MAX_LENGTH
    ):
        # Deliberately does not repeat the value back — this string ends up in
        # an error response and, from there, in someone's log aggregator.
        raise ValidationError(
            f"{field} must be {PIN_MIN_LENGTH}-{PIN_MAX_LENGTH} digits.",
        )
    return cleaned


def validate_otp_code(*, value: str, field: str = "otp_code") -> str:
    cleaned = sanitise_identifier(value=value, field=field, max_length=OTP_LENGTH)
    if not _DIGITS.match(cleaned) or len(cleaned) != OTP_LENGTH:
        raise ValidationError(f"{field} must be {OTP_LENGTH} digits.")
    return cleaned


def validate_referral_code(*, value: str, field: str = "referred_by_code") -> str:
    """Empty is fine — most sign-ups have no referrer."""
    cleaned = sanitise_identifier(value=value, field=field, max_length=12)
    if not cleaned:
        return ""
    if not _REFERRAL.match(cleaned):
        raise ValidationError(f"{field} is not a valid referral code.")
    return cleaned
