# Generated by Django 5.2.13 on 2026-04-27 11:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_units', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('total_aum', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('nav_per_unit', models.DecimalField(decimal_places=6, default=1, max_digits=18)),
                ('underlying', models.JSONField(default=list)),
                ('fund', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pool', to='funds.fund')),
            ],
            options={
                'db_table': 'pools_pool',
                'ordering': ['-created_at'],
            },
        ),
    ]
