# Generated by Django 5.2.15 on 2026-08-29 18:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_profiler', '0002_profiletemplate'),
        ('funds', '0006_hero_image_url_to_charfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='investorprofile',
            name='behaviour_vector',
            field=models.JSONField(blank=True, default=dict, help_text='Resolved anchor per behaviour — the input the profile match was made from'),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='imputed_behaviours',
            field=models.JSONField(blank=True, default=list, help_text='Behaviours filled with the population median rather than measured'),
        ),
        migrations.AddField(
            model_name='profiletemplate',
            name='category_weights',
            field=models.JSONField(blank=True, default=dict, help_text='Fund category to weight, used to rank within the risk band'),
        ),
        migrations.AddField(
            model_name='profiletemplate',
            name='centroid',
            field=models.JSONField(blank=True, default=dict, help_text='Target anchor per ordinal behaviour; matching is nearest centroid'),
        ),
        migrations.AddField(
            model_name='profiletemplate',
            name='max_funds',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='profiletemplate',
            name='risk_band',
            field=models.JSONField(blank=True, default=list, help_text='[min, max] Fund.risk_level this profile may be recommended'),
        ),
        migrations.AlterField(
            model_name='profiletemplate',
            name='playlist',
            field=models.ForeignKey(blank=True, help_text="Materialised cache of the funds matching this profile's criteria", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_templates', to='funds.playlist'),
        ),
        migrations.CreateModel(
            name='SessionQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveSmallIntegerField(help_text='1-indexed order the question was asked in')),
                ('primary_behaviour', models.CharField(db_index=True, max_length=20)),
                ('secondary_behaviours', models.JSONField(default=list)),
                ('source', models.CharField(choices=[('GENERATED', 'Generated'), ('FALLBACK', 'Fallback')], default='GENERATED', max_length=10)),
                ('prompt', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, default='', max_length=200)),
                ('options', models.JSONField(default=list, help_text='Options exactly as shown, each with its anchor tags')),
                ('selected_indexes', models.JSONField(default=list, help_text='Indexes into `options` that the user chose')),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='ai_profiler.conversationsession')),
            ],
            options={
                'db_table': 'ai_profiler_session_question',
                'ordering': ['session', 'position'],
                'constraints': [models.UniqueConstraint(fields=('session', 'position'), name='unique_session_question_position')],
            },
        ),
    ]
