# Generated by Django 5.2.15 on 2026-08-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_profiler', '0003_investorprofile_behaviour_vector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionquestion',
            name='revisions',
            field=models.JSONField(blank=True, default=list, help_text='Prior selections, appended when the user goes back and amends'),
        ),
        migrations.AddField(
            model_name='sessionquestion',
            name='superseded_at',
            field=models.DateTimeField(blank=True, help_text='Set when an earlier answer changed and made this question unsound', null=True),
        ),
    ]
