# Generated by Django 5.2.15 on 2026-08-31 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_profiler', '0004_sessionquestion_revisions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investorprofile',
            name='scoring_method',
            field=models.CharField(choices=[('RUBRIC', 'Anchored rubric'), ('LEGACY', 'Legacy keyword scorer')], db_index=True, default='RUBRIC', help_text='How this profile was derived; LEGACY rows are re-profilable', max_length=10),
        ),
    ]
