# Generated by Django 5.2.15 on 2026-09-22 17:44

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_profiler', '0005_investorprofile_scoring_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='PooledQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('behaviour', models.CharField(db_index=True, max_length=32)),
                ('prompt', models.CharField(max_length=160)),
                ('subtitle', models.CharField(blank=True, default='', max_length=200)),
                ('options', models.JSONField(default=list)),
                ('secondary_behaviours', models.JSONField(default=list)),
                ('source', models.CharField(choices=[('GENERATED', 'Generated'), ('FALLBACK', 'Fallback')], default='GENERATED', max_length=20)),
                ('claimed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'ai_profiler_pooled_question',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['behaviour', 'claimed_at', 'created_at'], name='pooled_q_available_idx')],
            },
        ),
    ]
