# Generated by Django 5.2.14 on 2026-06-14 17:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentLimit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kyc_tier', models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('BASIC', 'Basic'), ('FULL', 'Full')], max_length=20, unique=True)),
                ('max_per_transaction', models.DecimalField(decimal_places=2, max_digits=18)),
                ('max_per_month', models.DecimalField(decimal_places=2, max_digits=18)),
            ],
            options={
                'db_table': 'compliance_investment_limit',
            },
        ),
        migrations.CreateModel(
            name='ConsentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('TERMS', 'Terms of Service'), ('PRIVACY', 'Privacy Policy')], max_length=20)),
                ('version', models.CharField(max_length=20)),
                ('effective_date', models.DateField()),
                ('content_url', models.URLField()),
            ],
            options={
                'db_table': 'compliance_consent_version',
                'constraints': [models.UniqueConstraint(fields=('document_type', 'version'), name='unique_consent_doc_version')],
            },
        ),
        migrations.CreateModel(
            name='UserConsent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_at', models.DateTimeField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('consent_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acceptances', to='compliance.consentversion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'compliance_user_consent',
                'constraints': [models.UniqueConstraint(fields=('user', 'consent_version'), name='unique_user_consent_version')],
            },
        ),
    ]
