# Generated by Django 5.2.13 on 2026-04-26 03:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funds', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('units', models.DecimalField(decimal_places=6, max_digits=18)),
                ('nav_at_purchase', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('idempotency_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investments', to='funds.fund')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'investments_investment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_units', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('total_invested', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('average_nav', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holdings', to='funds.fund')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'investments_holding',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'fund'), name='unique_user_fund_holding')],
            },
        ),
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('total_invested', models.DecimalField(decimal_places=2, max_digits=18)),
                ('daily_change', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('daily_change_pct', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'investments_portfolio_snapshot',
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='unique_user_portfolio_date')],
            },
        ),
    ]
