# Generated by Django 5.2.15 on 2026-09-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_alter_investment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringplan',
            name='frequency',
            field=models.CharField(choices=[('ONE_OFF', 'One Off'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Bi-weekly'), ('MONTHLY', 'Monthly'), ('BIMONTHLY', 'Bi-monthly'), ('QUARTERLY', 'Quarterly'), ('HALF_YEARLY', 'Half Yearly'), ('YEARLY', 'Yearly')], max_length=20),
        ),
    ]
