# Generated by Django 5.2.15 on 2026-09-17 08:13

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0004_alter_recurringplan_frequency'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('min_contribution', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text="Smallest amount a recurring contribution may collect, in KES. Whole shillings only — M-Pesa Ratiba cannot deduct a fraction, so anything below 1 creates plans Safaricom rounds down to nothing. Separate from a fund's own minimum investment, which governs a lump sum bought in one go.", max_digits=18)),
            ],
            options={
                'verbose_name': 'Investment settings',
                'verbose_name_plural': 'Investment settings',
                'db_table': 'investments_settings',
            },
        ),
    ]
