# Generated by Django 5.2.13 on 2026-04-25 17:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('fund_type', models.CharField(choices=[('ETF', 'ETF'), ('FUND', 'Fund'), ('ASSET', 'Asset')], max_length=10)),
                ('category', models.CharField(choices=[('TECH', 'Technology'), ('BONDS', 'Bonds'), ('REAL_ESTATE', 'Real Estate'), ('CRYPTO', 'Crypto'), ('SUSTAINABILITY', 'Sustainability'), ('GENERAL', 'General')], max_length=20)),
                ('risk_level', models.IntegerField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Medium'), (4, 'High'), (5, 'Very High')])),
                ('currency', models.CharField(choices=[('KES', 'Kenyan Shilling'), ('USD', 'US Dollar')], max_length=3)),
                ('minimum_investment', models.DecimalField(decimal_places=2, max_digits=18)),
                ('lock_in_days', models.PositiveIntegerField(default=0)),
                ('projected_annual_return', models.DecimalField(decimal_places=2, max_digits=6)),
                ('effective_annual_yield', models.DecimalField(decimal_places=2, max_digits=6)),
                ('annualized_daily_yield', models.DecimalField(decimal_places=2, max_digits=6)),
                ('hero_image_url', models.URLField(blank=True, default='')),
                ('is_trending', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'funds_fund',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FundNAV',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('nav_value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('daily_change_pct', models.DecimalField(decimal_places=4, max_digits=8)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nav_history', to='funds.fund')),
            ],
            options={
                'db_table': 'funds_nav',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('fund', 'date'), name='unique_fund_nav_date')],
            },
        ),
        migrations.CreateModel(
            name='FundPerformance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.CharField(choices=[('1M', '1 Month'), ('3M', '3 Months'), ('6M', '6 Months'), ('1Y', '1 Year'), ('5Y', '5 Years')], max_length=5)),
                ('return_pct', models.DecimalField(decimal_places=4, max_digits=8)),
                ('start_value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('end_value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('calculated_at', models.DateTimeField()),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='funds.fund')),
            ],
            options={
                'db_table': 'funds_performance',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('fund', 'period'), name='unique_fund_performance_period')],
            },
        ),
    ]
