# Generated by Django 5.2.15 on 2026-07-28 18:50

import apps.common.storage
import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0002_playlist_playlistfund'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='aum',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Assets Under Management in USD', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='chart_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='fund',
            name='expense_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='fund_manager',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='fund',
            name='hero_image',
            field=models.ImageField(blank=True, default='', upload_to=apps.common.storage.hero_image_upload_path, validators=[apps.common.validators.validate_image_max_5mb]),
        ),
        migrations.AddField(
            model_name='fund',
            name='launched_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='listed_country',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='fund',
            name='management_type',
            field=models.CharField(blank=True, choices=[('PASSIVE', 'Passive'), ('ACTIVE', 'Active'), ('RULES_BASED', 'Rules-based passive')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='fund',
            name='perfect_for',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='fund',
            name='ticker_symbol',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='fund',
            name='top_holdings',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='fund',
            name='ytd_return',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='playlist',
            name='hero_image',
            field=models.ImageField(blank=True, default='', upload_to=apps.common.storage.hero_image_upload_path, validators=[apps.common.validators.validate_image_max_5mb]),
        ),
        migrations.AlterField(
            model_name='fund',
            name='category',
            field=models.CharField(choices=[('TECH', 'Technology'), ('SEMICONDUCTOR', 'Semiconductor'), ('DIVIDEND', 'Dividend'), ('DIVERSIFIED', 'Diversified'), ('BONDS', 'Bonds'), ('REAL_ESTATE', 'Real Estate'), ('CRYPTO', 'Crypto'), ('SUSTAINABILITY', 'Sustainability'), ('GENERAL', 'General')], max_length=20),
        ),
    ]
