# Generated by Django 5.2.15 on 2026-07-28 18:50

import apps.common.storage
import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0003_sync_existing_fund_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='hero_image',
            field=models.ImageField(blank=True, default='', upload_to=apps.common.storage.hero_image_upload_path, validators=[apps.common.validators.validate_image_max_5mb]),
        ),
        migrations.AddField(
            model_name='playlist',
            name='hero_image',
            field=models.ImageField(blank=True, default='', upload_to=apps.common.storage.hero_image_upload_path, validators=[apps.common.validators.validate_image_max_5mb]),
        ),
    ]
