# Generated by Django 5.2.15 on 2026-08-27 07:44

import apps.common.storage
import apps.common.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0004_add_hero_image_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='performance_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='fund',
            name='risk_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='FundHolding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('logo_image', models.ImageField(blank=True, default='', upload_to=apps.common.storage.holding_logo_upload_path, validators=[apps.common.validators.validate_image_max_5mb])),
                ('logo_url', models.URLField(blank=True, default='')),
                ('position', models.PositiveIntegerField(default=0)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_holdings', to='funds.fund')),
            ],
            options={
                'db_table': 'funds_fund_holding',
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(fields=('fund', 'name'), name='unique_fund_holding_name')],
            },
        ),
    ]
