# Generated by Django 5.2.15 on 2026-08-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0005_fund_performance_description_fund_risk_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='hero_image_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
