# Generated by Django 5.2.15 on 2026-09-04 04:57

import apps.common.storage
import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0006_hero_image_url_to_charfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='hero_image',
            field=models.ImageField(blank=True, default='', storage=apps.common.storage.PublicMediaStorage, upload_to=apps.common.storage.hero_image_upload_path, validators=[apps.common.validators.validate_image_max_5mb]),
        ),
        migrations.AlterField(
            model_name='fundholding',
            name='logo_image',
            field=models.ImageField(blank=True, default='', storage=apps.common.storage.PublicMediaStorage, upload_to=apps.common.storage.holding_logo_upload_path, validators=[apps.common.validators.validate_image_max_5mb]),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='hero_image',
            field=models.ImageField(blank=True, default='', storage=apps.common.storage.PublicMediaStorage, upload_to=apps.common.storage.hero_image_upload_path, validators=[apps.common.validators.validate_image_max_5mb]),
        ),
    ]
