from __future__ import annotations

from datetime import date
from decimal import Decimal

from apps.funds.models import Fund


def create_fund(
    *,
    name: str,
    slug: str,
    description: str,
    fund_type: str,
    category: str,
    risk_level: int,
    currency: str,
    minimum_investment: Decimal,
    lock_in_days: int = 0,
    projected_annual_return: Decimal,
    effective_annual_yield: Decimal,
    annualized_daily_yield: Decimal,
    ticker_symbol: str = "",
    performance_description: str = "",
    risk_description: str = "",
    expense_ratio: Decimal | None = None,
    aum: Decimal | None = None,
    ytd_return: Decimal | None = None,
    launched_date: date | None = None,
    management_type: str = "",
    listed_country: str = "",
    fund_manager: str = "",
    top_holdings: list | None = None,
    perfect_for: str = "",
    chart_url: str = "",
    hero_image_url: str = "",
    metadata: dict | None = None,
) -> Fund:
    return Fund.objects.create(
        name=name,
        slug=slug,
        description=description,
        fund_type=fund_type,
        category=category,
        risk_level=risk_level,
        currency=currency,
        minimum_investment=minimum_investment,
        lock_in_days=lock_in_days,
        projected_annual_return=projected_annual_return,
        effective_annual_yield=effective_annual_yield,
        annualized_daily_yield=annualized_daily_yield,
        ticker_symbol=ticker_symbol,
        performance_description=performance_description,
        risk_description=risk_description,
        expense_ratio=expense_ratio,
        aum=aum,
        ytd_return=ytd_return,
        launched_date=launched_date,
        management_type=management_type,
        listed_country=listed_country,
        fund_manager=fund_manager,
        top_holdings=top_holdings or [],
        perfect_for=perfect_for,
        chart_url=chart_url,
        hero_image_url=hero_image_url,
        metadata=metadata or {},
    )
