# Generated by Django 5.2.13 on 2026-04-25 17:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketTicker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('change_pct', models.DecimalField(decimal_places=4, max_digits=8)),
                ('change_value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('fetched_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'market_data_ticker',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_currency', models.CharField(max_length=3)),
                ('quote_currency', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=18)),
                ('source', models.CharField(max_length=50)),
                ('fetched_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'market_data_exchange_rate',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('base_currency', 'quote_currency'), name='unique_currency_pair')],
            },
        ),
    ]
