# Generated by Django 5.2.14 on 2026-06-14 17:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('MANUAL_REVIEW', 'Manual Review')], db_index=True, default='NOT_STARTED', max_length=20)),
                ('document_type', models.CharField(blank=True, choices=[('NATIONAL_ID', 'National ID'), ('PASSPORT', 'Passport'), ('DRIVING_LICENSE', 'Driving License')], default='', max_length=20)),
                ('smile_job_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('result_text', models.TextField(blank=True, default='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_submission', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kyc_submission',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KYCWebhookLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_payload', models.JSONField()),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('result_code', models.CharField(blank=True, default='', max_length=50)),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_logs', to='kyc.kycsubmission')),
            ],
            options={
                'db_table': 'kyc_webhook_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KYCDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('side', models.CharField(choices=[('FRONT', 'Front'), ('BACK', 'Back'), ('SELFIE', 'Selfie')], max_length=10)),
                ('file_key', models.CharField(max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='kyc.kycsubmission')),
            ],
            options={
                'db_table': 'kyc_document',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('submission', 'side'), name='unique_submission_side')],
            },
        ),
    ]
